AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Exclude:
    - "lib/concise_errors/formatter.rb"

Metrics/MethodLength:
  Exclude:
    - "lib/concise_errors/formatter.rb"
